/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.mkdev.employee.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EmployeeDetail service. Represents a row in the &quot;mkdev_EmployeeDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.mkdev.employee.model.impl.EmployeeDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.mkdev.employee.model.impl.EmployeeDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetail
 * @see org.mkdev.employee.model.impl.EmployeeDetailImpl
 * @see org.mkdev.employee.model.impl.EmployeeDetailModelImpl
 * @generated
 */
@ProviderType
public interface EmployeeDetailModel extends BaseModel<EmployeeDetail>,
	ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee detail model instance should use the {@link EmployeeDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this employee detail.
	 *
	 * @return the primary key of this employee detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee detail.
	 *
	 * @param primaryKey the primary key of this employee detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee detail.
	 *
	 * @return the uuid of this employee detail
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee detail.
	 *
	 * @param uuid the uuid of this employee detail
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the emp ID of this employee detail.
	 *
	 * @return the emp ID of this employee detail
	 */
	public long getEmpId();

	/**
	 * Sets the emp ID of this employee detail.
	 *
	 * @param empId the emp ID of this employee detail
	 */
	public void setEmpId(long empId);

	/**
	 * Returns the group ID of this employee detail.
	 *
	 * @return the group ID of this employee detail
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this employee detail.
	 *
	 * @param groupId the group ID of this employee detail
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee detail.
	 *
	 * @return the company ID of this employee detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee detail.
	 *
	 * @param companyId the company ID of this employee detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee detail.
	 *
	 * @return the user ID of this employee detail
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this employee detail.
	 *
	 * @param userId the user ID of this employee detail
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee detail.
	 *
	 * @return the user uuid of this employee detail
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee detail.
	 *
	 * @param userUuid the user uuid of this employee detail
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this employee detail.
	 *
	 * @return the create date of this employee detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee detail.
	 *
	 * @param createDate the create date of this employee detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee detail.
	 *
	 * @return the modified date of this employee detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee detail.
	 *
	 * @param modifiedDate the modified date of this employee detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this employee detail.
	 *
	 * @return the first name of this employee detail
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this employee detail.
	 *
	 * @param firstName the first name of this employee detail
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this employee detail.
	 *
	 * @return the last name of this employee detail
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this employee detail.
	 *
	 * @param lastName the last name of this employee detail
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this employee detail.
	 *
	 * @return the email of this employee detail
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this employee detail.
	 *
	 * @param email the email of this employee detail
	 */
	public void setEmail(String email);

	/**
	 * Returns the age of this employee detail.
	 *
	 * @return the age of this employee detail
	 */
	public int getAge();

	/**
	 * Sets the age of this employee detail.
	 *
	 * @param age the age of this employee detail
	 */
	public void setAge(int age);

	/**
	 * Returns the gender of this employee detail.
	 *
	 * @return the gender of this employee detail
	 */
	public int getGender();

	/**
	 * Sets the gender of this employee detail.
	 *
	 * @param gender the gender of this employee detail
	 */
	public void setGender(int gender);

	/**
	 * Returns the address of this employee detail.
	 *
	 * @return the address of this employee detail
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this employee detail.
	 *
	 * @param address the address of this employee detail
	 */
	public void setAddress(String address);

	/**
	 * Returns the mobile of this employee detail.
	 *
	 * @return the mobile of this employee detail
	 */
	@AutoEscape
	public String getMobile();

	/**
	 * Sets the mobile of this employee detail.
	 *
	 * @param mobile the mobile of this employee detail
	 */
	public void setMobile(String mobile);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EmployeeDetail employeeDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EmployeeDetail> toCacheModel();

	@Override
	public EmployeeDetail toEscapedModel();

	@Override
	public EmployeeDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}